### ISSUE TITLE
Missing BODY example in  Delete task list

### ISSUE THREAD

**Issue by ricsxn** [indigo-dc/FutureGateway-APIs#1]
There is no a BODY example for Delete task list; I'm expecting something like: 
```
{ tasks: [ 1,2,3,...,] 
}
```

**Comment by fmarco76** [comment]
Generally, the HTTP DELETE can return status code 200 and something in the body, or 204 and empty body. In the case of FutureGateway APIs the second approach is followed.

For more information: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by fmarco76** [comment]
If the BODY was for the client then it is useless because the DELETE in the REST APIs acts on the entire collection.

For more information: https://en.wikipedia.org/wiki/Representational_state_transfer
